---
name: markdown-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: articulate/actions-markdownlint@v1
