---
name: markdown-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - uses: articulate/actions-markdownlint@v1
