---
name: markdown-lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: markdown-lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - uses: articulate/actions-markdownlint@v1
